apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  data:
    - secretKey: creds
      remoteRef:
        key: secret/crossplane/aws
        property: creds
